### ISSUE TITLE
message with time

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/slock-flexipatch#1]
Is there a way to show the date/time using the message patch? Obviously it won't update on its own, I'd have to write a script that kills the slock process every minute and relaunches it.

**Comment by bakkeby** [comment]
No I am not aware of anything like this. I suspect to get something like a date/time thing to work then you'd have to change the while loop in the `readpw` function to use a mechanism along the lines of the first post in https://stackoverflow.com/questions/8592292/how-to-quit-the-blocking-of-xlibs-xnextevent

**Comment by plasmoduck** [comment]
Fair enough, thanks.
