### ISSUE TITLE
new patches

### ISSUE THREAD

**Issue by plasmoduck** [bakkeby/slock-flexipatch#5]
Hi mate, there are a few new patches, if you could add them please that would be great.

This patch draws a dwm logo on the locked screen - https://tools.suckless.org/slock/patches/dwmlogo/
This patch combines the dwm logo and pixelate+blur patches and adds xft support for nicer fonts - https://tools.suckless.org/slock/patches/foreground-and-background/

**Comment by bakkeby** [comment]
I added the dwm logo patch, for the foreground-and-background patch just combine the dwm logo patch with the blur pixelated screen patch. Personally I think it looks better with the dwm logo + alpha + compositor blurring the background.

The foreground and background patch doesn't actually do anything with regards to Xft, it has a line `#include <X11/Xft/Xft.h>`, but it doesn't actually use anything from that library. I suspect it is something that the author of the patch has left in there by mistake.

**Comment by plasmoduck** [comment]
This is an error after compiling.

 In file included from slock.c:96:
./config.h:7:3: error: use of undeclared identifier 'BACKGROUND'
        [BACKGROUND] =  "#2d2d2d", /* after initialization */

**Comment by bakkeby** [comment]
Right, the background should not be defined if the blur pixelated screen patch is enabled, added a fix for that just now.
