### ISSUE TITLE
fans spin up af and temps rise af

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/slock-flexipatch#7]
1. Hi, so even without any patches, my fans spin up crazy and my temps rise when using your slock build.
This does not happen when I install from the arch repos.
```
slock build options:
CFLAGS   = -std=c99 -pedantic -Wall -Os -I. -I/usr/include -I/usr/X11R6/include -DVERSION="1.4" -D_DEFAULT_SOURCE -DHAVE_SHADOW_H 
LDFLAGS  = -s -L/usr/lib -lc -lcrypt -L/usr/X11R6/lib -lX11 -lXext -lXrandr   
CC       = cc
creating config.h from config.def.h
creating patches.h from patches.def.h
CC slock.c
CC explicit_bzero.c
CC -o slock
installing executable file to /usr/local/bin
installing manual page to /usr/local/share/man/man1
```

No errors, user I set as my user and group nobody as said in the config.

2. Oh and why no make uninstall option on dmenu-flexipatch and slock-flexipatch? That would be nice.

**Comment by bakkeby** [comment]
Have you applied any patches?

**Comment by der-zonk** [comment]
As I said I had no patches applied.. but now this happend, I rebooted and now it works no problems, at least with only dpms patch. More I don't really need..

Could this cause an issue? I had slock from the arch repos installed, uninstalled it, installed your slock and ran it and then the heat increase happened.. Does one need to relogin or something? This is the first time I had such an issue..

**Comment by bakkeby** [comment]
I have seen this maybe once after trying to manually kill slock, not sure exactly. I assume that it is hard to replicate. 

If you do not have any patches enabled then there should not be any functional differences with this build compared to a stock slock build. 

As for there being no uninstall option in the make file; I guess the author(s) of the original projects did not think that anyone would ever want to uninstall their software :)

Although it would be introducing something that is not part of the original project I think it would be feasible to add.

**Comment by der-zonk** [comment]
So the issue is still there. I narrowed it down to the auto timeout patch. Ipatched with dpms, no problem, after that I tried quickcancel on top, no problem, then I tried auto timeout on top, fans spin up crazy and temps rise..

**Comment by bakkeby** [comment]
So do you think that it has something to do with the auto timeout patch then?

**Comment by bakkeby** [comment]
I suppose the author of that patch could have added a sleep or usleep call in there.

**Comment by der-zonk** [comment]
> So do you think that it has something to do with the auto timeout patch then?

Since it started after applying that patch I would guess so but I can't read nor write c code so I can't really tell nor troubleshoot..

**Comment by bakkeby** [comment]
Can you try with the above change to see if that makes any difference?

**Comment by der-zonk** [comment]
Yes this works. Is this adding a one time sleep or is it hitting every 50 milliseconds? And why even?

**Comment by bakkeby** [comment]
It would be every 50 milliseconds.

The patch changes the while loops so that rather than only evaluating when there are new events to process it will continuously check whether now is the time to execute the timeout command. This could easily mean that it would be checking this 500 times per second. Adding a sleep of 50ms cuts this down to 20 times per second.

You could change this to 500ms or a whole second of course, but you may want to double check if this has an effect on typing in your password to unlock it etc. as it could potentially add some lag.

**Comment by der-zonk** [comment]
Thanks a lot!
